/**
 * Registry metadata for dynamic demo generation.
 * Static component JSONs are generated by `shadcn build` from registry.json
 */

export interface RegistryItemMeta {
  name: string;
  description: string;
  folder?: "ui" | "animated";
  dependencies?: string[];
  registryDependencies?: string[];
}

export const registry: Record<string, RegistryItemMeta> = {
  "card-icons": {
    name: "card-icons",
    description: "Shared card brand icons and types for billing components.",
    dependencies: ["lucide-react"],
    registryDependencies: [],
  },
  "card-input": {
    name: "card-input",
    description:
      "Native formatted card inputs with auto-formatting, brand detection, and masking for demos and custom PSPs.",
    dependencies: ["lucide-react"],
    registryDependencies: ["https://billui.com/r/card-icons.json"],
  },
  "payment-form": {
    name: "payment-form",
    description:
      "A composable, provider-agnostic payment form wrapper for Stripe, Braintree, or native inputs.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "https://billui.com/r/card-input.json"],
  },
  "plan-card": {
    name: "plan-card",
    description: "A card for displaying pricing tiers and subscription plans.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge"],
  },
  "plan-group": {
    name: "plan-group",
    description:
      "A container for displaying multiple pricing plans with a monthly/yearly toggle.",
    registryDependencies: ["https://billui.com/r/plan-card.json"],
  },
  "invoice-card": {
    name: "invoice-card",
    description: "A card for displaying invoice details and billing history.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge"],
  },
  "payment-method": {
    name: "payment-method",
    description:
      "A card for displaying saved payment methods like credit cards.",
    dependencies: ["lucide-react"],
    registryDependencies: [
      "button",
      "badge",
      "https://billui.com/r/card-icons.json",
    ],
  },
  "usage-card": {
    name: "usage-card",
    description:
      "A card for displaying usage metrics, billing cycle progress and itemized charges.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "progress"],
  },
  "animated-usage-card": {
    name: "animated-usage-card",
    description:
      "An animated version of usage-card with smooth spring animations powered by motion.",
    folder: "animated",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: ["button"],
  },
  "pricing-table": {
    name: "pricing-table",
    description:
      "A comparison table for displaying multiple pricing plans side by side with feature comparison.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button"],
  },
};

// For components-list.tsx
export const registryIndex = {
  items: Object.values(registry).map(({ name, description }) => ({
    name,
    type: "registry:ui",
    description,
  })),
};

export function getRegistryItem(name: string): RegistryItemMeta | undefined {
  return registry[name];
}
