/**
 * Registry metadata for dynamic demo generation.
 * Static component JSONs are generated by `shadcn build` from registry.json
 */

export interface RegistryItemMeta {
  name: string;
  description: string;
  folder?: "ui" | "animated";
  dependencies?: string[];
  registryDependencies?: string[];
}

export const registry: Record<string, RegistryItemMeta> = {
  "plan-card": {
    name: "plan-card",
    description: "A card for displaying pricing tiers and subscription plans.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge"],
  },
  "plan-group": {
    name: "plan-group",
    description:
      "A container for displaying multiple pricing plans with a monthly/yearly toggle.",
    registryDependencies: ["https://billui.com/r/plan-card.json"],
  },
  "invoice-card": {
    name: "invoice-card",
    description: "A card for displaying invoice details and billing history.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge"],
  },
  "payment-method": {
    name: "payment-method",
    description:
      "A card for displaying saved payment methods like credit cards.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge"],
  },
  "usage-card": {
    name: "usage-card",
    description:
      "A card for displaying usage metrics, billing cycle progress and itemized charges.",
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "progress"],
  },
  "animated-usage-card": {
    name: "animated-usage-card",
    description:
      "An animated version of usage-card with smooth spring animations powered by motion.",
    folder: "animated",
    dependencies: ["lucide-react", "motion"],
    registryDependencies: ["button"],
  },
};

// For components-list.tsx
export const registryIndex = {
  items: Object.values(registry).map(({ name, description }) => ({
    name,
    type: "registry:ui",
    description,
  })),
};

export function getRegistryItem(name: string): RegistryItemMeta | undefined {
  return registry[name];
}
